BDOG-1690 Fix replaceIndexes for index rename
hmrc/hmrc-mongo pull request #83
Opened 2022-02-21 12:05 UTC by colin-lamed

2022-02-21 16:14 UTC, Shnick submitted a review, later dismissed

2022-02-22 11:46 UTC, chotai requested changes
If we have multiple instances of an app running, could we potentially run into issues where try to drop and recreate the orphaned indexes multiple times? Should we use a transaction here?

2022-02-22 11:46 UTC, chotai commented on hmrc-mongo-common/src/main/scala/uk/gov/hmrc/mongo/MongoUtils.scala
> +                              Future.successful(logger.warn(s"The following indices exist in mongo for ${collection.namespace}, but are (no longer) provided to ensureIndexes: ${orphanedIndices.mkStri
Although indices and indexes are both correct as the plural for index, as mongo has already fixed on indexes - and we have used indexes too (like in ensureIndexes), I feel we should just use indexes through out. I would replace all occurrences of indices with indexes.

2022-02-22 11:46 UTC, chotai commented on hmrc-mongo-common/src/main/scala/uk/gov/hmrc/mongo/MongoUtils.scala
> +                              Future.successful(logger.warn(s"The following indices exist in mongo for ${collection.namespace}, but are (no longer) provided to ensureIndexes: ${orphanedIndices.mkStri
We should log the keys that make up the index as well imo - will be useful to detect where a index has been renamed and would be a good addition for the mongo 4.2 index change

Should we log the keys and indexes passed to ensureIndexes as well?

2022-02-23 09:43 UTC, colin-lamed commented
It's not possible to edit indexes within a transaction. I can't really think of a way to avoid this (without mongo lock).
I think it would be very rare (race condition in the scenario that there's a deployment with an index update) and this approach is already being used (also from simple-reactivemongo) and I'm not aware of having seen this being an issue so far.

2022-02-23 11:22 UTC, chotai approved these changes, later dismissed

2022-02-23 11:22 UTC, chotai commented on hmrc-mongo-common/src/main/scala/uk/gov/hmrc/mongo/MongoUtils.scala
> +      orphanedIndexes  =  existingIndexes
could we use `existingIndexMap.keys()` here instead?

2022-02-23 11:22 UTC, chotai commented on hmrc-mongo-common/src/main/scala/uk/gov/hmrc/mongo/MongoUtils.scala
> +                            Future.successful(logger.warn(s"The following indexes exist in mongo for ${collection.namespace}, but are (no longer) provided to ensure: $str"))
should `ensure` be `ensureIndexes`?

2022-02-23 11:22 UTC, chotai commented on hmrc-mongo-common/src/main/scala/uk/gov/hmrc/mongo/MongoUtils.scala
> +                              logger.warn(s"Index '$orphanName' key: '${existingIndexMap(orphanName)("key")}' is no longer defined for ${collection.namespace}, removing")
Wonder is "removing" should be made more explicit. eg "dropping index.."

2022-02-23 11:36 UTC, chotai approved these changes

2022-02-23 11:40 UTC, merged